[project]
name = "lite-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "litellm>=1.72.6",
    "python-env>=1.0.0",
]
